const songs=[
 {title:"Chhath Bhakti Special",artist:"Chhath Bhakti",src:"songs/chhath-01.mp3",cover:"assets/cover-1.svg",category:"Bhakti"},
 {title:"Chhath ghate chli",artist:"Singer Name",src:"songs/song-10.mp3",cover:"assets/cover-1.svg",category:"New Added"},
 {title:"ChalS Bhauji Hali Hali",artist:"Sonu Nigam & Pawan Singh",src:"songs/chhath-02.mp3",cover:"assets/cover-2.svg",category:"Chhath Special"},
 {title:"Chhathi Maiya Bulaye",artist:"Vishal Mishra",src:"songs/chhath-03.mp3",cover:"assets/cover-3.svg",category:"Devotional"},
 {title:"Aditya Gosaiya",artist:"Pawan Singh",src:"songs/chhath-04.mp3",cover:"assets/cover-1.svg",category:"Chhath Geet"},
 {title:"Chhath Puja Special",artist:"Chhath Bhakti",src:"songs/chhath-05.mp3",cover:"assets/cover-2.svg",category:"Bhakti"},
 {title:"Koshiya Bharaye Lagal",artist:"Neelkamal Singh & Priyanka Singh",src:"songs/chhath-06.mp3",cover:"assets/cover-3.svg",category:"Bhojpuri Chhath"},
 {title:"New Chhath Song 1",artist:"Chhath Bhakti",src:"songs/song-07.mp3",cover:"assets/cover-1.svg",category:"New Added"},
 {title:"New Chhath Song 2",artist:"Chhath Bhakti",src:"songs/song-08.mp3",cover:"assets/cover-2.svg",category:"New Added"},
 {title:"New Chhath Song 3",artist:"Chhath Bhakti",src:"songs/song-09.mp3",cover:"assets/cover-3.svg",category:"New Added"}
];

const audio=document.getElementById('audio'),playBtn=document.getElementById('playBtn'),prevBtn=document.getElementById('prevBtn'),nextBtn=document.getElementById('nextBtn'),shuffleBtn=document.getElementById('shuffleBtn'),repeatBtn=document.getElementById('repeatBtn'),progress=document.getElementById('progress'),volume=document.getElementById('volume'),currentTime=document.getElementById('currentTime'),duration=document.getElementById('duration'),playerTitle=document.getElementById('playerTitle'),playerArtist=document.getElementById('playerArtist'),playerCover=document.getElementById('playerCover'),playerFavorite=document.getElementById('playerFavorite'),songList=document.getElementById('songList'),albumGrid=document.getElementById('albumGrid'),search=document.getElementById('search'),songCount=document.getElementById('songCount'),sortSelect=document.getElementById('sortSelect'),toast=document.getElementById('toast');
let index=0,shuffle=false,repeat=false,autoplay=true,view='home';
let favorites=JSON.parse(localStorage.getItem('chhath-favorites')||'[]');
let downloads=JSON.parse(localStorage.getItem('chhath-downloads')||'[]');
const savedIndex=Number(localStorage.getItem('chhath-last-index')); if(Number.isInteger(savedIndex)&&savedIndex>=0&&savedIndex<songs.length) index=savedIndex;
function fmt(t){if(!Number.isFinite(t))return '0:00';return `${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`}
function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function isFav(i){return favorites.includes(i)}
function save(){localStorage.setItem('chhath-favorites',JSON.stringify(favorites));localStorage.setItem('chhath-downloads',JSON.stringify(downloads));localStorage.setItem('chhath-last-index',index)}
function load(i,autoplayNow=false){index=(i+songs.length)%songs.length;const s=songs[index];audio.src=s.src;playerTitle.textContent=s.title;playerArtist.textContent=s.artist;playerCover.src=s.cover;progress.value=0;currentTime.textContent='0:00';duration.textContent='0:00';playerFavorite.textContent=isFav(index)?'♥':'♡';playerFavorite.classList.toggle('active',isFav(index));save();renderSongs();if(autoplayNow)play()}
async function play(){try{await audio.play();playBtn.textContent='Ⅱ'}catch(e){showToast('Audio file could not be played') }}function pause(){audio.pause();playBtn.textContent='▶'}
playBtn.onclick=()=>audio.paused?play():pause();
prevBtn.onclick=()=>{if(audio.currentTime>3){audio.currentTime=0;return} load(index-1,true)};
nextBtn.onclick=()=>{let n=shuffle?Math.floor(Math.random()*songs.length):index+1;load(n,true)};
shuffleBtn.onclick=()=>{shuffle=!shuffle;shuffleBtn.classList.toggle('on',shuffle);showToast(shuffle?'Shuffle on':'Shuffle off')};
repeatBtn.onclick=()=>{repeat=!repeat;repeatBtn.classList.toggle('on',repeat);showToast(repeat?'Repeat on':'Repeat off')};
audio.addEventListener('timeupdate',()=>{if(audio.duration){progress.value=(audio.currentTime/audio.duration)*100;currentTime.textContent=fmt(audio.currentTime)}});audio.addEventListener('loadedmetadata',()=>duration.textContent=fmt(audio.duration));
progress.oninput=()=>{if(audio.duration)audio.currentTime=(progress.value/100)*audio.duration};volume.oninput=()=>audio.volume=Number(volume.value);audio.volume=.85;
audio.addEventListener('ended',()=>{if(repeat){audio.currentTime=0;play()}else if(autoplay)nextBtn.click();else pause()});
playerFavorite.onclick=()=>{favorites=isFav(index)?favorites.filter(x=>x!==index):[...favorites,index];save();playerFavorite.textContent=isFav(index)?'♥':'♡';playerFavorite.classList.toggle('active',isFav(index));renderSongs();showToast(isFav(index)?'Added to Favorites':'Removed from Favorites')};
function filtered(){let q=search.value.trim().toLowerCase();let arr=songs.map((s,i)=>({...s,i}));if(view==='favorites')arr=arr.filter(x=>isFav(x.i));if(view==='downloads')arr=arr.filter(x=>downloads.includes(x.i));if(view==='artists')arr=arr.filter(x=>true);if(q)arr=arr.filter(x=>`${x.title} ${x.artist} ${x.category}`.toLowerCase().includes(q));const sort=sortSelect.value;if(sort==='title')arr.sort((a,b)=>a.title.localeCompare(b.title));if(sort==='artist')arr.sort((a,b)=>a.artist.localeCompare(b.artist));if(sort==='duration')arr.sort((a,b)=>(b.i-a.i));return arr}
function renderSongs(){const arr=filtered();songCount.textContent=`${arr.length}`;songList.innerHTML='';document.getElementById('emptyState').hidden=arr.length>0;arr.forEach((s,pos)=>{const row=document.createElement('div');row.className='song-row'+(s.i===index?' playing':'');row.innerHTML=`<div class="song-no">${pos+1}</div><img class="thumb" src="${s.cover}" alt=""><div class="song-main"><strong>${s.title}</strong><span>${s.category}</span></div><div class="song-artist">${s.artist}</div><div class="song-duration">${s.i===index&&audio.duration?fmt(audio.duration):'—'}</div><button class="row-btn favorite ${isFav(s.i)?'active':''}" title="Favorite">${isFav(s.i)?'♥':'♡'}</button><button class="row-btn row-download ${downloads.includes(s.i)?'downloaded':''}" title="Download">⇩</button><button class="row-btn row-more" title="More">⋮</button>`;
row.querySelector('.song-main').onclick=()=>load(s.i,true);row.querySelector('.thumb').onclick=()=>load(s.i,true);row.querySelector('.song-no').onclick=()=>load(s.i,true);row.querySelector('.favorite').onclick=()=>toggleFav(s.i);row.querySelector('.row-download').onclick=()=>downloadSong(s.i);songList.appendChild(row)})}
function toggleFav(i){favorites=isFav(i)?favorites.filter(x=>x!==i):[...favorites,i];save();if(i===index){playerFavorite.textContent=isFav(i)?'♥':'♡';playerFavorite.classList.toggle('active',isFav(i))}renderSongs();showToast(isFav(i)?'Added to Favorites':'Removed from Favorites')}
function downloadSong(i){const a=document.createElement('a');a.href=songs[i].src;a.download=songs[i].src.split('/').pop();document.body.appendChild(a);a.click();a.remove();if(!downloads.includes(i))downloads.push(i);save();renderSongs();showToast('Download started')}
function renderAlbums(){albumGrid.innerHTML='';songs.slice(0,5).forEach((s,i)=>{const c=document.createElement('article');c.className='album-card';c.innerHTML=`<div class="album-cover"><img src="${s.cover}" alt=""><button class="cover-play">▶</button></div><div class="album-info"><h3>${s.title}</h3><p>${s.artist}</p></div>`;c.querySelector('button').onclick=()=>load(i,true);albumGrid.appendChild(c)})}
search.oninput=renderSongs;sortSelect.onchange=renderSongs;
document.getElementById('playAllBtn').onclick=()=>{load(0,true);document.getElementById('songsSection').scrollIntoView({behavior:'smooth'})};document.getElementById('scrollSongs').onclick=()=>document.getElementById('songsSection').scrollIntoView({behavior:'smooth'});document.getElementById('viewAll').onclick=()=>document.getElementById('songsSection').scrollIntoView({behavior:'smooth'});
document.querySelectorAll('.nav-item[data-view]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-item[data-view]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');view=btn.dataset.view;document.getElementById('popularSection').style.display=(view==='home'||view==='playlist'||view==='albums')?'block':'none';document.getElementById('songsSection').style.display=(view==='about')?'none':'block';if(view==='about')document.getElementById('aboutSection').scrollIntoView({behavior:'smooth'});else if(view==='favorites'||view==='downloads'||view==='artists'){document.getElementById('songsSection').scrollIntoView({behavior:'smooth'})}else window.scrollTo({top:0,behavior:'smooth'});renderSongs();if(window.innerWidth<=760)document.getElementById('sidebar').classList.remove('open')});
document.getElementById('menuBtn').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
function toggleTheme(){document.body.classList.toggle('light');localStorage.setItem('chhath-theme',document.body.classList.contains('light')?'light':'dark');document.getElementById('themeBtn').textContent=document.body.classList.contains('light')?'☾':'☼'}document.getElementById('themeBtn').onclick=toggleTheme;document.getElementById('modalTheme').onclick=toggleTheme;
const savedTheme=localStorage.getItem('chhath-theme'); if(savedTheme==='dark'){document.body.classList.remove('light');document.getElementById('themeBtn').textContent='☼'}else{document.body.classList.add('light');document.getElementById('themeBtn').textContent='☾';}
document.getElementById('settingsBtn').onclick=()=>document.getElementById('settingsModal').hidden=false;document.getElementById('closeModal').onclick=()=>document.getElementById('settingsModal').hidden=true;document.getElementById('autoplayToggle').onchange=e=>autoplay=e.target.checked;
document.getElementById('notifyBtn').onclick=()=>showToast('जय छठी मैया ❤️');document.getElementById('queueBtn').onclick=()=>showToast(`${songs.length} songs in your library`);
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.focus()}if(e.code==='Space'&&document.activeElement.tagName!=='INPUT'){e.preventDefault();audio.paused?play():pause()}if(e.key==='ArrowRight'&&e.altKey)nextBtn.click();if(e.key==='ArrowLeft'&&e.altKey)prevBtn.click()});
renderAlbums();load(index,false);
